services:
  db_test:
    image: pgvector/pgvector:pg17
    container_name: countrydle_test_db
    environment:
      POSTGRES_DB: guess_country_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_test_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d guess_country_test"]
      interval: 5s
      timeout: 5s
      retries: 10
